# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6d58a822131fb552264710a1069dabc4d4ccb148adacd1e3d06ae0d58185e197e3e27a9e4637290a81fbcba3719c99dda907fc7d67d6aa9cc5d6a88c07359f8

test:
  secret_key_base: bd41ac3ac8d3054389af7d27fef349dc92d0fae11a669f563064cd89e834d315d7129b1bca71815e34b07b296406cbac716c1b3a3cfcb4ca846d359c578a61fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
